apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opencomponents-registry.fullname" . }}-config-env
  labels: {{- include "opencomponents-registry.labels" . | nindent 4 }}
data:
  .env: |
    BASE_URL={{ .Values.config.baseUrl }}
    COMPONENTS_DIR={{ .Values.config.componentsDir }}

    S3_DEBUG={{ .Values.config.s3.debug }}
    S3_USE_SSL={{ .Values.config.s3.ssl }}
    S3_FORCE_PATH_STYLE={{ .Values.config.s3.forcePathStyle }}

    S3_REGION={{ .Values.config.s3.region }}
    S3_ENDPOINT={{ .Values.config.s3.endpoint }}
    S3_PATH={{ .Values.config.s3.path }}
    S3_BUCKET={{ .Values.config.s3.bucket }}

