apiVersion: v1
kind: Secret
metadata:
  name: {{ include "opencomponents-registry.fullname" . }}-secret-env
  labels: {{- include "opencomponents-registry.labels" . | nindent 4 }}
stringData:
  .env: |-
    {{- if .Values.config.s3.secret.enabled }}
    S3_ACCCESS_KEY={{ .Values.config.s3.secret.access_key }}
    S3_SECRET_KEY={{ .Values.config.s3.secret.secret_key }}
    {{- end }}

    {{- if .Values.config.publishAuth.enabled }}
    PUBLISH_USERNAME={{ .Values.config.publishAuth.username }}
    PUBLISH_PASSWORD={{ .Values.config.publishAuth.password }}
    {{- end }}